<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Title_ThankYou</name>
   <tag></tag>
   <elementGuidId>45b569f5-9c64-47cc-8520-e9ddb2a14e28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>h1.requestSuccessTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>h1.requestSuccessTitle</value>
   </webElementProperties>
</WebElementEntity>
