<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Company_field</name>
   <tag></tag>
   <elementGuidId>cf3fa5ec-4303-4465-b990-9c3d31a30db8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[name='organization_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[name='organization_name']</value>
   </webElementProperties>
</WebElementEntity>
