<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fullname_field</name>
   <tag></tag>
   <elementGuidId>159b0f2a-806a-40b4-bc42-bca217675514</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[name='name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[name='name']</value>
   </webElementProperties>
</WebElementEntity>
