<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubmitBtn</name>
   <tag></tag>
   <elementGuidId>23f5187c-2525-499e-9be7-d90fc9ee6ef8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.el-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.el-button</value>
   </webElementProperties>
</WebElementEntity>
