<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_menu</name>
   <tag></tag>
   <elementGuidId>613f7645-b7a2-4e79-8c50-41b4feb4dc0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.white[href='/login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.white[href='/login']</value>
   </webElementProperties>
</WebElementEntity>
