<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Request_Demo_Menu</name>
   <tag></tag>
   <elementGuidId>9223a682-56e0-4d79-82b8-f74089a97c2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.signup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.signup</value>
   </webElementProperties>
</WebElementEntity>
