<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Sign Up Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>45ab3ea7-6c9b-497f-a38e-acd7fd13b12f</testSuiteGuid>
   <testCaseLink>
      <guid>c51924d8-fab4-4262-8941-57a81ae24854</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign Up/All fields are filled</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c45fd2e6-0c7c-4382-af81-b105033d859d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e4d0599-e041-4b87-8ddf-bf0f2f589841</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2247675c-3095-4e45-be9f-0dbc56e9399f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66eaeca2-287b-4013-afb2-35a1e6e5e1a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d07f4fb3-61d8-4441-a344-29919fa5c012</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb2f693c-76ac-4640-b583-4fcf10c0e408</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign Up/Company field is null</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e469654-d2e6-4da3-8bb9-42f48e9186d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94d32462-b5bc-4a8d-83b4-3dc113b8090f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43b34710-f831-4874-9208-b75fd6d0b625</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d702fd2-4c71-4047-9421-5672d8208f8a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94a274b5-4e17-4561-b91b-ab9fb19dab03</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6007b00-e345-41f0-aadd-55e5a08be63c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign Up/Email field is null</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5281d7b0-a1dc-4cce-ae63-67568312f18e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5da420b9-422c-4330-ae8e-60c794ed0680</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b6db87f-1c23-494e-94e7-af05aaf87ee6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ef6a68c-f277-45ec-acdb-4d9a5326a2d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e3a818f-db6f-47d8-9df4-409562b2f9a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>afe1a40c-19f6-423c-ba5a-d3d2de6f5be8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign Up/Full Name field is null</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd4e0112-a59d-4b2e-94cc-58e571046a30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0420ca2f-87ba-48ad-9261-d318ba96ed72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7a85ef6-277a-4195-8f6b-ae422adc9245</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3369476a-cdee-4a4b-bc3d-b6df42d80804</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea2b4bfa-c6a3-4817-be91-5583717eeda9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b6098b7-da2c-4576-ae54-fb45ca291c27</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sign Up/Phone number field is null</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8c9fb81-deb5-45e3-bae2-77d1f3bdec13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20e6069b-bd24-4c3b-852d-e0a6f39642be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1d52414-85b2-4936-89e0-eb4bd8930b59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bf0cb4c-6686-4097-b030-451756db2d7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b59c81c1-cd22-42cb-8f30-aa3db0d654ee</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
