<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test All Field</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d22265d5-9fc7-480a-a1de-a91284164c6d</testSuiteGuid>
   <testCaseLink>
      <guid>f3b6b3ab-6adb-4ca7-9f2a-6ca1b5967352</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Company field/Delete all characters after input</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>412e257f-22f2-4cc2-a551-cb3da83cecd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ca78a06-ba59-4848-9de6-0760b462edae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>710891ca-45e3-4309-bbd5-1b77910fc2ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63d9db6f-887a-474d-8a33-8bda04684d81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f895466-9c84-49e6-9c27-360aaef1f3d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c1142f7-ccd0-467c-b042-b16bcc8c9f91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21e54d19-9dbb-42ca-ad93-72c9c9c1d63e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Email name field/Delete all characters after input</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46f9015d-3d9f-4110-a56f-ab913d3f6acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>750f90d8-e044-4a12-a26b-50c26d747849</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16f475c6-86f4-4327-adf4-a744b3cab00a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ad70d3a-f410-4b49-9913-35e9c6c54dda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>910e7079-1df5-4ce5-9b12-991c81d656fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24fbc29d-28fb-4ef9-b8a2-05c4bef5235b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be47bafa-0a7e-4566-bd9c-dd70788d39f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Email name field/Not format email input</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>667c7689-fa13-48d2-b73b-99e4cec1146c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Full name field/Delete all characters after input</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3aa6951e-67c3-4249-8c32-644a05d086da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fde84689-e760-4ee1-b825-26e04f9dfbae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f849efd9-4b17-4ec0-9825-13139dcfc1a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19198552-03f4-4408-8e19-f2bfac4a0364</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afa07231-78ad-4300-b3b9-07717951882d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0591dcf4-15c9-43a1-896d-5e455e3db865</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24a91735-4c8e-46a3-900f-e28e98a4050f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Phone field/Delete all characters after input</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e02f3548-db94-4d1e-b6a1-9638d568895d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>033f3e86-872b-463d-aa92-72899669c8e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbce9013-a211-4a5b-8b0d-e37be5a82fd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65b0438b-0b9a-4541-bd8d-9f547c7c3875</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91208834-7977-47bf-b45f-7835d5c5900f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42f84ad2-053c-4646-8381-8aacf84f79aa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c145148d-60c0-48ab-8030-59b56babcabf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Phone field/Only alphabet input</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
